### ISSUE TITLE
An option to hide all scores

### ISSUE THREAD

**Issue by suhr** [tiensonqin/lambdahackers#14]
For Reddit I have the following userstyle:

```css
.score {
    opacity: 0.0;
}

.tagline .score {
    display: none !important;
}

small .score {
    display: none !important;
}

.search-score {
    display: none !important;
}
```

This little trick helps me to not be distracted by numbers and pay attention to the content instead of blindly following the crowd.

For LambdaHackers, It would be nice to have an actual option in the settings.
